# Generated by Django 5.0 on 2024-01-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='company_competencies', to='hr_admin.competency'),
        ),
        migrations.CreateModel(
            name='CompetencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('achieved_number', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_records', to='hr_admin.company')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.competency')),
            ],
        ),
    ]
