# Generated by Django 4.2.9 on 2024-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0002_competency_company_competencies_competencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsanswer',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
