# Generated by Django 4.2.9 on 2024-02-01 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Strategy', 'Strategy'), ('Recruiting', 'Recruiting'), ('Retraining-Employee-Development', 'Retraining (Employee Development)'), ('Retaining-Performance-Management', 'Retaining (Performance Management)'), ('Retaining-Compensation-Benefits', 'Retaining (Compensation and Benefits)'), ('Retaining-Internal-Communication', 'Retaining (Internal Communication, Other Benefits)'), ('Turnover', 'Turnover')], max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company_form_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('NA', 'NA'), ('Yes', 'Yes'), ('No', 'No')], default='NA', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.company_form')),
            ],
            options={
                'unique_together': {('company', 'question')},
            },
        ),
    ]
