# Generated by Django 4.2.9 on 2024-02-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0005_company_form_company_form_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_form',
            new_name='CompanyForm',
        ),
        migrations.RenameModel(
            old_name='company_form_answers',
            new_name='CompanyFormAnswers',
        ),
    ]
