# Generated by Django 4.2.9 on 2024-02-01 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_admin', '0006_rename_company_form_companyform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
