# Generated by Django 4.2.9 on 2024-02-02 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_admin', '0007_alter_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='direction_strategy',
        ),
        migrations.RemoveField(
            model_name='company',
            name='exports_of_revenue',
        ),
        migrations.RemoveField(
            model_name='company',
            name='initiatives_projects',
        ),
        migrations.RemoveField(
            model_name='company',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='company',
            name='management',
        ),
        migrations.RemoveField(
            model_name='company',
            name='official_governmental_websites',
        ),
        migrations.RemoveField(
            model_name='company',
            name='professional_staff',
        ),
        migrations.RemoveField(
            model_name='company',
            name='recent_strategy_or_planning_document',
        ),
        migrations.RemoveField(
            model_name='company',
            name='trade_industry_references',
        ),
        migrations.RemoveField(
            model_name='company',
            name='web_search',
        ),
        migrations.AddField(
            model_name='company',
            name='initiatives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='marketing_channels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
