# Generated by Django 4.2.9 on 2024-02-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0008_remove_company_direction_strategy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name_of_ceo_md',
            new_name='ceo',
        ),
        migrations.AddField(
            model_name='company',
            name='gm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
