# Generated by Django 4.2.9 on 2024-02-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0009_rename_name_of_ceo_md_company_ceo_company_gm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.TextField(blank=True, null=True, verbose_name='Products/Services'),
        ),
    ]
