# Generated by Django 4.2.9 on 2024-02-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0011_remove_company_organizational_people_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyformanswers',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companyformanswers',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyformanswers',
            name='question',
        ),
        migrations.DeleteModel(
            name='CompanyForm',
        ),
        migrations.DeleteModel(
            name='CompanyFormAnswers',
        ),
    ]
