# Generated by Django 4.2.9 on 2024-02-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0012_alter_companyformanswers_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='photo',
        ),
    ]
