# Generated by Django 4.2.9 on 2024-02-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0013_remove_consultant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LinkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
