# Generated by Django 4.2.9 on 2024-02-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0014_remove_consultant_email_remove_consultant_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputscategory',
            name='InputsForm',
        ),
        migrations.AddField(
            model_name='inputsquestion',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_admin.inputsform'),
        ),
    ]
