# Generated by Django 4.2.9 on 2024-02-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0015_remove_inputscategory_inputsform_inputsquestion_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.inputsform'),
        ),
    ]
